modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="worldrestore"
version="1.0.0"
displayName="World Restore"
description='''
Restores the world from a template zip on every server start.
'''

[[dependencies.worldrestore]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.worldrestore]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="SERVER"
